apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: dev 
spec: 
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  mountOptions:
    - hard 
    - nfsvers=4.1
  nfs: 
    path: /mnt/share
    server: 172.31.86.186


--- 

apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc 
  namespace: dev 
spec: 
  storageClassName: manual 
  resources:
    requests: 
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
