apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  namespace: dev
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: springapp
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 30
  template: 
    metadata:
      name: springapp
      labels:
        app: springapp
    spec: 
      containers:
      - name: springapp
        image: acadalearning/spring-boot-mongo
        ports:
        - containerPort: 8080
        env: 
        - name: MONGO_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: springapp-cm
              key: john
        - name: MONGO_DB_PASSWORD 
          valueFrom:
            secretKeyRef: 
              name: mongo-passwd
              key: db-passwd
        - name: MONGO_DB_HOSTNAME
          valueFrom: 
            configMapKeyRef:
              name: springapp-cm
              key: mongo-hn

apiVersion: v1 
kind: Service 
metadata:
  name: springapp
  namespace: dev
spec: 
  type: NodePort
  selector: 
    app: springapp
  ports: 
  - targetPort: 8080
    port: 80
    protocol: TCP
    nodePort: 32000
